import { fromXML } from "./parsing";

export class Entry {
  entryID: number;
  categoryID: number;
  eventID: number;
  contactID: number;
  entryStatusEnum: string;
  addressTypeID: number;
  bookingID: number;
  entryApplicationID: number;
  pinNumber: number;
  password: string;
  portalEmail: string;
  portalAuthProviderUserID: string;
  portalPasswordHash: string | null;
  portalPasswordSalt: string | null;
  portalResetGUID: string;
  conferenceEmail: string;
  agentPassword: string;
  agentPasswordResetGuid: string | null;
  agentPasswordResetExpiryDate: string | null;
  nameLast: string;
  nameFirst: string;
  nameTitle: string;
  namePreferred: string;
  nameWeb: string;
  nameOther: string;
  nameInitials: string;
  nameSharer: string;
  genderEnum: string;
  birthGenderEnum: string;
  directoryFlagPrivacy: boolean;
  dob: string | null;
  position: string;
  id1: string;
  id2: string;
  id3: string;
  id4: number;
  id5: number;
  phoneProcessToAccount: boolean;
  phoneChargeTypeID: number;
  phoneDisableValue: number;
  phoneRestrictValue: number;
  phoneControlEnum: string;
  taxExemptionEnum: string;
  lastCheckInOutDate: string | null;
  previousEntryStatusEnum: string;
  testing: boolean;
  userSecurityUserID: number;
  securityUserID: number;
  createdBySecurityUserID: number;
  dateCreated: string;
  entryGUID: string;
  timestamp: string;
  dateModified: string;

  constructor(xml: string | Node) {
    const data = fromXML(xml, "Entry");

    if (!data) {
      throw new Error('Invalid XML');
    }

    this.entryID = data.entryID ?? 0;
    this.categoryID = data.categoryID ?? 0;
    this.eventID = data.eventID ?? 0;
    this.contactID = data.contactID ?? 0;
    this.entryStatusEnum = data.entryStatusEnum ?? '';
    this.addressTypeID = data.addressTypeID ?? 0;
    this.bookingID = data.bookingID ?? 0;
    this.entryApplicationID = data.entryApplicationID ?? 0;
    this.pinNumber = data.pinNumber ?? 0;
    this.password = data.password ?? '';
    this.portalEmail = data.portalEmail ?? '';
    this.portalAuthProviderUserID = data.portalAuthProviderUserID ?? '';
    this.portalPasswordHash = data.portalPasswordHash ?? null;
    this.portalPasswordSalt = data.portalPasswordSalt ?? null;
    this.portalResetGUID = data.portalResetGUID ?? '';
    this.conferenceEmail = data.conferenceEmail ?? '';
    this.agentPassword = data.agentPassword ?? '';
    this.agentPasswordResetGuid = data.agentPasswordResetGuid ?? null;
    this.agentPasswordResetExpiryDate = data.agentPasswordResetExpiryDate ?? null;
    this.nameLast = data.nameLast ?? '';
    this.nameFirst = data.nameFirst ?? '';
    this.nameTitle = data.nameTitle ?? '';
    this.namePreferred = data.namePreferred ?? '';
    this.nameWeb = data.nameWeb ?? '';
    this.nameOther = data.nameOther ?? '';
    this.nameInitials = data.nameInitials ?? '';
    this.nameSharer = data.nameSharer ?? '';
    this.genderEnum = data.genderEnum ?? '';
    this.birthGenderEnum = data.birthGenderEnum ?? '';
    this.directoryFlagPrivacy = data.directoryFlagPrivacy ?? false;
    this.dob = data.dob ?? null;
    this.position = data.position ?? '';
    this.id1 = data.id1 ?? '';
    this.id2 = data.id2 ?? '';
    this.id3 = data.id3 ?? '';
    this.id4 = data.id4 ?? 0;
    this.id5 = data.id5 ?? 0;
    this.phoneProcessToAccount = data.phoneProcessToAccount ?? false;
    this.phoneChargeTypeID = data.phoneChargeTypeID ?? 0;
    this.phoneDisableValue = data.phoneDisableValue ?? 0;
    this.phoneRestrictValue = data.phoneRestrictValue ?? 0;
    this.phoneControlEnum = data.phoneControlEnum ?? '';
    this.taxExemptionEnum = data.taxExemptionEnum ?? '';
    this.lastCheckInOutDate = data.lastCheckInOutDate ?? null;
    this.previousEntryStatusEnum = data.previousEntryStatusEnum ?? '';
    this.testing = data.testing ?? false;
    this.userSecurityUserID = data.userSecurityUserID ?? 0;
    this.securityUserID = data.securityUserID ?? 0;
    this.createdBySecurityUserID = data.createdBySecurityUserID ?? 0;
    this.dateCreated = data.dateCreated ?? '';
    this.entryGUID = data.entryGUID ?? '';
    this.timestamp = data.timestamp ?? '';
    this.dateModified = data.dateModified ?? '';
  }
}
